apiVersion: hpc.rosalita.github.io/v1
kind: DistributedJob
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: distributedjob-sample
spec:
  workerReplicas: 3
  image: "busybox:1.28"
  command: ["sh", "-c", "echo 'Hello from worker!' && sleep 3600"]
